#/odom_world: /visual_slam/odom
#/grid_map/odom: /visual_slam/odom
#/grid_map/cloud: /pcl_render_node/camera_pose
#/grid_map/pose: /pcl_render_node/depth
#/grid_map/depth: /pcl_render_node/cloud

fsm/flight_type: 1
fsm/thresh_replan: 1.5
fsm/thresh_no_replan: 2.0
fsm/planning_horizon: 2.5
fsm/planning_horizen_time: 3
fsm/emergency_time_: 1.0

# params.yaml
grid_map:
  resolution: 0.1
  map_size_x: 40.0
  map_size_y: 40.0
  map_size_z: 3.0
  local_update_range_x: 5.5
  local_update_range_y: 5.5
  local_update_range_z: 4.5
  obstacles_inflation: 0.099
  local_map_margin: 30
  ground_height: -0.01
  cx: 321.04638671875
  cy: 243.44969177246094
  fx: 387.229248046875
  fy: 387.229248046875
  use_depth_filter: true
  depth_filter_tolerance: 0.15
  depth_filter_maxdist: 5.0
  depth_filter_mindist: 0.2
  depth_filter_margin: 1
  k_depth_scaling_factor: 1000.0
  skip_pixel: 2
  p_hit: 0.65
  p_miss: 0.35
  p_min: 0.12
  p_max: 0.90
  p_occ: 0.80
  min_ray_length: 0.1
  max_ray_length: 4.5
  virtual_ceil_height: 2.5
  visualization_truncate_height: 2.4
  show_occ_time: false
  pose_type: 2
  frame_id: world

manager:
  max_vel: 2.0
  max_acc: 2.0
  max_jerk: 4
  control_points_distance: 0.4
  feasibility_tolerance: 0.05
  planning_horizon: 7.5

optimization:
  lambda_smooth: 1.0
  lambda_collision: 0.5
  lambda_feasibility: 0.1
  lambda_fitness: 1.0
  dist0: 0.5
  max_vel: 2.0
  max_acc: 2.0

bspline:
  limit_vel: 2.0
  limit_acc: 2.0
  limit_ratio: 1.1

